receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318
      grpc:
        endpoint: 0.0.0.0:4317

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  debug:
    verbosity: detailed
  
  # Zipkin exporter
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"
    format: proto
  
  # OTLP exporter for Jaeger
  otlp:
    endpoint: jaeger:4317
    tls:
      insecure: true
  
  # Uncomment these sections when you're ready to send data to other backends
  # prometheus:
  #   endpoint: 0.0.0.0:8889
  #   namespace: otel-demo

service:
  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug, zipkin, otlp]
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [debug]
